/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/assets/enterPortal.gltf
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import enterPortalModel from './enterPortal.gltf';

export default function Model(props) {
  const { nodes, materials } = useGLTF(enterPortalModel);

  useEffect(() => {
    console.log('Materials:', materials)
  }, [materials])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus.geometry} material={nodes.Torus.material} position={[0, 2.07, 0]} rotation={[Math.PI / 2, 0, 0]} scale={4.63} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.001']} position={[-16.09, 2.84, -44.68]} rotation={[Math.PI / 2, 0, -1.63]} scale={1.05} />
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[-17.2, 0, -58.88]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-3.31, 0.71, 9.4]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.1, 0.67, 0.1]} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-5.63, 2.57, -65.63]} rotation={[Math.PI / 2, 0, 0]} scale={[2.61, 0.32, 2.61]} />
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[-17.35, 3.46, -48.38]} rotation={[0, -1.52, 0]} scale={[-4.97, -1.12, -0.85]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-3.27, 1.87, 9.33]} rotation={[0, 0.53, 0]} scale={[0.92, 0.54, 0.1]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[22.27, 2.49, -48.51]} rotation={[Math.PI, -1.54, Math.PI]} scale={[9.03, 3.36, 4.52]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-21.12, 2.49, -47.71]} rotation={[-Math.PI, 1.52, -Math.PI]} scale={[9.03, 2.52, 4.52]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-19.66, 10.8, -66.78]} rotation={[0, 0.53, 0]} scale={[7.15, 11.39, 4.21]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[23.52, 2.49, -79.45]} rotation={[0, -0.5, 0]} scale={[9.03, 2.52, 4.52]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} rotation={[0, 0, -Math.PI]} scale={[-5.58, -0.25, -47.21]} />
    </group>
  )
}

useGLTF.preload(enterPortalModel);
